### ISSUE TITLE
Adjust blog entries snippet colors

### ISSUE THREAD

**Issue by keybatte** [Everything-Explained/web-client#20]
- change the pink highlighted detail of words in b.s to a white. And the pink underling to more of a burgendy red. More subtle but noticeable againts the default silver color

**Comment by Jaeiya** [comment]
The way it works right now, the blog entries are just using the default style from the rest of the text styling and you'll notice it's using the same red color highlight that the rest of the site uses to display highlighted text.

For the blog entries list snippets, I could just remove all styling if that would look better? Bold text is already colored in white, so that wouldn't make them distinct.

**Comment by Jaeiya** [comment]
811e45ed120f3bbbc2dad2c87f7620c655c40b25 adds a proper summary property for blog entries, which doesn't allow any markup.
